#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurgo.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public enum msdynmkt_handlingduplicateleads
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Usearuletomatchanexistinglead = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Alwayscreatenewlead = 100000001,
	}
}
#pragma warning restore CS1591
