#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurgo.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public enum msdynmkt_marketingform_msdynmkt_portalpublishingstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotStarted = 534120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Publishing = 534120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 534120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Succeeded = 534120004,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public enum msdynmkt_msdynmkt_marketingform_msdynmkt_standalonepublishstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotStarted = 534120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 534120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 534120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Succeeded = 534120004,
	}
	
	/// <summary>
	/// Status of the Form
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public enum msdynmkt_marketingform_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Form
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public enum msdynmkt_marketingform_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Live = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LiveEditing = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 100,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdynmkt_marketingform")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.15")]
	public partial class msdynmkt_marketingform : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the msdynmkt_marketingform entity
		/// </summary>
		public partial class Fields
		{
			public const string ComponentIdUnique = "componentidunique";
			public const string ComponentState = "componentstate";
			public const string componentstateName = "componentstatename";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string IsCustomizable = "iscustomizable";
			public const string IsManaged = "ismanaged";
			public const string ismanagedName = "ismanagedname";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string msdynmkt_compliancesettings4id = "msdynmkt_compliancesettings4id";
			public const string msdynmkt_compliancesettings4idName = "msdynmkt_compliancesettings4idname";
			public const string msdynmkt_conditionalcontent = "msdynmkt_conditionalcontent";
			public const string msdynmkt_contactmatchingrule = "msdynmkt_contactmatchingrule";
			public const string msdynmkt_contactmatchingruleName = "msdynmkt_contactmatchingrulename";
			public const string msdynmkt_createcontact = "msdynmkt_createcontact";
			public const string msdynmkt_createcontactName = "msdynmkt_createcontactname";
			public const string msdynmkt_createlead = "msdynmkt_createlead";
			public const string msdynmkt_createleadName = "msdynmkt_createleadname";
			public const string msdynmkt_createnewparentcontactonnomatch = "msdynmkt_createnewparentcontactonnomatch";
			public const string msdynmkt_createnewparentcontactonnomatchName = "msdynmkt_createnewparentcontactonnomatchname";
			public const string msdynmkt_designerhtml = "msdynmkt_designerhtml";
			public const string msdynmkt_doubleoptintogglemodifiedby = "msdynmkt_doubleoptintogglemodifiedby";
			public const string msdynmkt_doubleoptintogglemodifiedbyName = "msdynmkt_doubleoptintogglemodifiedbyname";
			public const string msdynmkt_doubleoptintogglemodifiedbyYomiName = "msdynmkt_doubleoptintogglemodifiedbyyominame";
			public const string msdynmkt_doubleoptintogglemodifiedon = "msdynmkt_doubleoptintogglemodifiedon";
			public const string msdynmkt_errormessage = "msdynmkt_errormessage";
			public const string msdynmkt_formhtml = "msdynmkt_formhtml";
			public const string msdynmkt_handlingduplicatecontacts = "msdynmkt_handlingduplicatecontacts";
			public const string msdynmkt_handlingduplicatecontactsName = "msdynmkt_handlingduplicatecontactsname";
			public const string msdynmkt_handlingduplicateleads = "msdynmkt_handlingduplicateleads";
			public const string msdynmkt_handlingduplicateleadsName = "msdynmkt_handlingduplicateleadsname";
			public const string msdynmkt_ignoreemptyfields = "msdynmkt_ignoreemptyfields";
			public const string msdynmkt_ignoreemptyfieldsName = "msdynmkt_ignoreemptyfieldsname";
			public const string msdynmkt_isdoiforciblydisabled = "msdynmkt_isdoiforciblydisabled";
			public const string msdynmkt_isdoiforciblydisabledName = "msdynmkt_isdoiforciblydisabledname";
			public const string msdynmkt_leadmatchingrule = "msdynmkt_leadmatchingrule";
			public const string msdynmkt_leadmatchingruleName = "msdynmkt_leadmatchingrulename";
			public const string msdynmkt_linkleadtoparentcontact = "msdynmkt_linkleadtoparentcontact";
			public const string msdynmkt_linkleadtoparentcontactName = "msdynmkt_linkleadtoparentcontactname";
			public const string msdynmkt_marketingformId = "msdynmkt_marketingformid";
			public const string Id = "msdynmkt_marketingformid";
			public const string msdynmkt_marketingformtemplateid = "msdynmkt_marketingformtemplateid";
			public const string msdynmkt_marketingformtemplateidName = "msdynmkt_marketingformtemplateidname";
			public const string msdynmkt_marketingformtype = "msdynmkt_marketingformtype";
			public const string msdynmkt_marketingformtypeName = "msdynmkt_marketingformtypename";
			public const string msdynmkt_matchingstrategyid = "msdynmkt_matchingstrategyid";
			public const string msdynmkt_matchingstrategyidName = "msdynmkt_matchingstrategyidname";
			public const string msdynmkt_name = "msdynmkt_name";
			public const string msdynmkt_parentcontactmatchingstrategyid = "msdynmkt_parentcontactmatchingstrategyid";
			public const string msdynmkt_parentcontactmatchingstrategyidName = "msdynmkt_parentcontactmatchingstrategyidname";
			public const string msdynmkt_placeholders = "msdynmkt_placeholders";
			public const string msdynmkt_portalpublishingstatus = "msdynmkt_portalpublishingstatus";
			public const string msdynmkt_portalpublishingstatusName = "msdynmkt_portalpublishingstatusname";
			public const string msdynmkt_portalurl = "msdynmkt_portalurl";
			public const string msdynmkt_Postsubmissionactions = "msdynmkt_postsubmissionactions";
			public const string msdynmkt_postsubmissionactionsName = "msdynmkt_postsubmissionactionsname";
			public const string msdynmkt_prefillfields = "msdynmkt_prefillfields";
			public const string msdynmkt_prefillfieldsName = "msdynmkt_prefillfieldsname";
			public const string msdynmkt_redirectenabled = "msdynmkt_redirectenabled";
			public const string msdynmkt_redirectenabledName = "msdynmkt_redirectenabledname";
			public const string msdynmkt_redirecturl = "msdynmkt_redirecturl";
			public const string msdynmkt_standalonehtml = "msdynmkt_standalonehtml";
			public const string msdynmkt_standalonepublishstatus = "msdynmkt_standalonepublishstatus";
			public const string msdynmkt_standalonepublishstatusName = "msdynmkt_standalonepublishstatusname";
			public const string msdynmkt_successmessage = "msdynmkt_successmessage";
			public const string msdynmkt_targetaudience = "msdynmkt_targetaudience";
			public const string msdynmkt_targetaudienceName = "msdynmkt_targetaudiencename";
			public const string msdynmkt_targetentity = "msdynmkt_targetentity";
			public const string msdynmkt_uniquename = "msdynmkt_uniquename";
			public const string msdynmkt_updatecontact = "msdynmkt_updatecontact";
			public const string msdynmkt_updatecontactName = "msdynmkt_updatecontactname";
			public const string msdynmkt_updatelead = "msdynmkt_updatelead";
			public const string msdynmkt_updateleadName = "msdynmkt_updateleadname";
			public const string msdynmkt_updateparentcontact = "msdynmkt_updateparentcontact";
			public const string msdynmkt_updateparentcontactName = "msdynmkt_updateparentcontactname";
			public const string msdynmkt_waitlistmessage = "msdynmkt_waitlistmessage";
			public const string msdynmkt_webtracking = "msdynmkt_webtracking";
			public const string msdynmkt_webtrackingName = "msdynmkt_webtrackingname";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OverwriteTime = "overwritetime";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string SolutionId = "solutionid";
			public const string statecode = "statecode";
			public const string statecodeName = "statecodename";
			public const string statuscode = "statuscode";
			public const string statuscodeName = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public msdynmkt_marketingform() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "msdynmkt_marketingform";
		
		public const string EntityLogicalCollectionName = "msdynmkt_marketingforms";
		
		public const string EntitySetName = "msdynmkt_marketingforms";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
		public System.Nullable<System.Guid> ComponentIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public virtual componentstate? ComponentState
		{
			get
			{
				return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstatename")]
		public string componentstateName
		{
			get
			{
				if (this.FormattedValues.Contains("componentstate"))
				{
					return this.FormattedValues["componentstate"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
		public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
			}
			set
			{
				this.OnPropertyChanging("IsCustomizable");
				this.SetAttributeValue("iscustomizable", value);
				this.OnPropertyChanged("IsCustomizable");
			}
		}
		
		/// <summary>
		/// Indicates whether the solution component is part of a managed solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanagedname")]
		public string ismanagedName
		{
			get
			{
				if (this.FormattedValues.Contains("ismanaged"))
				{
					return this.FormattedValues["ismanaged"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for Compliance profile associated with Form.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_compliancesettings4id")]
		public Microsoft.Xrm.Sdk.EntityReference msdynmkt_compliancesettings4id
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdynmkt_compliancesettings4id");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_compliancesettings4id");
				this.SetAttributeValue("msdynmkt_compliancesettings4id", value);
				this.OnPropertyChanged("msdynmkt_compliancesettings4id");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_compliancesettings4idname")]
		public string msdynmkt_compliancesettings4idName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_compliancesettings4id"))
				{
					return this.FormattedValues["msdynmkt_compliancesettings4id"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_conditionalcontent")]
		public string msdynmkt_conditionalcontent
		{
			get
			{
				return this.GetAttributeValue<string>("msdynmkt_conditionalcontent");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_conditionalcontent");
				this.SetAttributeValue("msdynmkt_conditionalcontent", value);
				this.OnPropertyChanged("msdynmkt_conditionalcontent");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_contactmatchingrule")]
		public Microsoft.Xrm.Sdk.EntityReference msdynmkt_contactmatchingrule
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdynmkt_contactmatchingrule");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_contactmatchingrule");
				this.SetAttributeValue("msdynmkt_contactmatchingrule", value);
				this.OnPropertyChanged("msdynmkt_contactmatchingrule");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_contactmatchingrulename")]
		public string msdynmkt_contactmatchingruleName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_contactmatchingrule"))
				{
					return this.FormattedValues["msdynmkt_contactmatchingrule"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_createcontact")]
		public virtual msdynmkt_formaudiencematchingchoice? msdynmkt_createcontact
		{
			get
			{
				return ((msdynmkt_formaudiencematchingchoice?)(EntityOptionSetEnum.GetEnum(this, "msdynmkt_createcontact")));
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_createcontact");
				this.SetAttributeValue("msdynmkt_createcontact", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("msdynmkt_createcontact");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_createcontactname")]
		public string msdynmkt_createcontactName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_createcontact"))
				{
					return this.FormattedValues["msdynmkt_createcontact"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_createlead")]
		public virtual msdynmkt_formaudiencematchingchoice? msdynmkt_createlead
		{
			get
			{
				return ((msdynmkt_formaudiencematchingchoice?)(EntityOptionSetEnum.GetEnum(this, "msdynmkt_createlead")));
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_createlead");
				this.SetAttributeValue("msdynmkt_createlead", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("msdynmkt_createlead");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_createleadname")]
		public string msdynmkt_createleadName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_createlead"))
				{
					return this.FormattedValues["msdynmkt_createlead"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// (Deprecated) When selected we'll try to create a new contact if there was no match to an existing one
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_createnewparentcontactonnomatch")]
		public System.Nullable<bool> msdynmkt_createnewparentcontactonnomatch
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdynmkt_createnewparentcontactonnomatch");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_createnewparentcontactonnomatch");
				this.SetAttributeValue("msdynmkt_createnewparentcontactonnomatch", value);
				this.OnPropertyChanged("msdynmkt_createnewparentcontactonnomatch");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_createnewparentcontactonnomatchname")]
		public string msdynmkt_createnewparentcontactonnomatchName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_createnewparentcontactonnomatch"))
				{
					return this.FormattedValues["msdynmkt_createnewparentcontactonnomatch"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Marked-up HTML used by Form Editor
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_designerhtml")]
		public string msdynmkt_designerhtml
		{
			get
			{
				return this.GetAttributeValue<string>("msdynmkt_designerhtml");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_designerhtml");
				this.SetAttributeValue("msdynmkt_designerhtml", value);
				this.OnPropertyChanged("msdynmkt_designerhtml");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the Is Double Opt-In Forcibly Disabled column.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_doubleoptintogglemodifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference msdynmkt_doubleoptintogglemodifiedby
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdynmkt_doubleoptintogglemodifiedby");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_doubleoptintogglemodifiedby");
				this.SetAttributeValue("msdynmkt_doubleoptintogglemodifiedby", value);
				this.OnPropertyChanged("msdynmkt_doubleoptintogglemodifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_doubleoptintogglemodifiedbyname")]
		public string msdynmkt_doubleoptintogglemodifiedbyName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_doubleoptintogglemodifiedby"))
				{
					return this.FormattedValues["msdynmkt_doubleoptintogglemodifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_doubleoptintogglemodifiedbyyominame")]
		public string msdynmkt_doubleoptintogglemodifiedbyYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_doubleoptintogglemodifiedby"))
				{
					return this.FormattedValues["msdynmkt_doubleoptintogglemodifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the Is Double Opt-In Forcibly Disabled column was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_doubleoptintogglemodifiedon")]
		public System.Nullable<System.DateTime> msdynmkt_doubleoptintogglemodifiedon
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdynmkt_doubleoptintogglemodifiedon");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_doubleoptintogglemodifiedon");
				this.SetAttributeValue("msdynmkt_doubleoptintogglemodifiedon", value);
				this.OnPropertyChanged("msdynmkt_doubleoptintogglemodifiedon");
			}
		}
		
		/// <summary>
		/// Error message
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_errormessage")]
		public string msdynmkt_errormessage
		{
			get
			{
				return this.GetAttributeValue<string>("msdynmkt_errormessage");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_errormessage");
				this.SetAttributeValue("msdynmkt_errormessage", value);
				this.OnPropertyChanged("msdynmkt_errormessage");
			}
		}
		
		/// <summary>
		/// Finilized HTML served to C2
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_formhtml")]
		public string msdynmkt_formhtml
		{
			get
			{
				return this.GetAttributeValue<string>("msdynmkt_formhtml");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_formhtml");
				this.SetAttributeValue("msdynmkt_formhtml", value);
				this.OnPropertyChanged("msdynmkt_formhtml");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_handlingduplicatecontacts")]
		public virtual msdynmkt_handlingduplicatecontacts? msdynmkt_handlingduplicatecontacts
		{
			get
			{
				return ((msdynmkt_handlingduplicatecontacts?)(EntityOptionSetEnum.GetEnum(this, "msdynmkt_handlingduplicatecontacts")));
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_handlingduplicatecontacts");
				this.SetAttributeValue("msdynmkt_handlingduplicatecontacts", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("msdynmkt_handlingduplicatecontacts");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_handlingduplicatecontactsname")]
		public string msdynmkt_handlingduplicatecontactsName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_handlingduplicatecontacts"))
				{
					return this.FormattedValues["msdynmkt_handlingduplicatecontacts"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_handlingduplicateleads")]
		public virtual msdynmkt_handlingduplicateleads? msdynmkt_handlingduplicateleads
		{
			get
			{
				return ((msdynmkt_handlingduplicateleads?)(EntityOptionSetEnum.GetEnum(this, "msdynmkt_handlingduplicateleads")));
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_handlingduplicateleads");
				this.SetAttributeValue("msdynmkt_handlingduplicateleads", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("msdynmkt_handlingduplicateleads");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_handlingduplicateleadsname")]
		public string msdynmkt_handlingduplicateleadsName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_handlingduplicateleads"))
				{
					return this.FormattedValues["msdynmkt_handlingduplicateleads"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_ignoreemptyfields")]
		public System.Nullable<bool> msdynmkt_ignoreemptyfields
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdynmkt_ignoreemptyfields");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_ignoreemptyfields");
				this.SetAttributeValue("msdynmkt_ignoreemptyfields", value);
				this.OnPropertyChanged("msdynmkt_ignoreemptyfields");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_ignoreemptyfieldsname")]
		public string msdynmkt_ignoreemptyfieldsName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_ignoreemptyfields"))
				{
					return this.FormattedValues["msdynmkt_ignoreemptyfields"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// If yes, Double Opt-In will be disabled for this marketing form, even if the form's compliance profile has Double Opt-In enabled.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_isdoiforciblydisabled")]
		public System.Nullable<bool> msdynmkt_isdoiforciblydisabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdynmkt_isdoiforciblydisabled");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_isdoiforciblydisabled");
				this.SetAttributeValue("msdynmkt_isdoiforciblydisabled", value);
				this.OnPropertyChanged("msdynmkt_isdoiforciblydisabled");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_isdoiforciblydisabledname")]
		public string msdynmkt_isdoiforciblydisabledName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_isdoiforciblydisabled"))
				{
					return this.FormattedValues["msdynmkt_isdoiforciblydisabled"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_leadmatchingrule")]
		public Microsoft.Xrm.Sdk.EntityReference msdynmkt_leadmatchingrule
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdynmkt_leadmatchingrule");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_leadmatchingrule");
				this.SetAttributeValue("msdynmkt_leadmatchingrule", value);
				this.OnPropertyChanged("msdynmkt_leadmatchingrule");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_leadmatchingrulename")]
		public string msdynmkt_leadmatchingruleName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_leadmatchingrule"))
				{
					return this.FormattedValues["msdynmkt_leadmatchingrule"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// (Deprecated) When selected we'll try to find a parent contact for a lead
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_linkleadtoparentcontact")]
		public System.Nullable<bool> msdynmkt_linkleadtoparentcontact
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdynmkt_linkleadtoparentcontact");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_linkleadtoparentcontact");
				this.SetAttributeValue("msdynmkt_linkleadtoparentcontact", value);
				this.OnPropertyChanged("msdynmkt_linkleadtoparentcontact");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_linkleadtoparentcontactname")]
		public string msdynmkt_linkleadtoparentcontactName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_linkleadtoparentcontact"))
				{
					return this.FormattedValues["msdynmkt_linkleadtoparentcontact"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_marketingformid")]
		public System.Nullable<System.Guid> msdynmkt_marketingformId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msdynmkt_marketingformid");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_marketingformId");
				this.SetAttributeValue("msdynmkt_marketingformid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("msdynmkt_marketingformId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_marketingformid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.msdynmkt_marketingformId = value;
			}
		}
		
		/// <summary>
		/// Form template
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_marketingformtemplateid")]
		public Microsoft.Xrm.Sdk.EntityReference msdynmkt_marketingformtemplateid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdynmkt_marketingformtemplateid");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_marketingformtemplateid");
				this.SetAttributeValue("msdynmkt_marketingformtemplateid", value);
				this.OnPropertyChanged("msdynmkt_marketingformtemplateid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_marketingformtemplateidname")]
		public string msdynmkt_marketingformtemplateidName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_marketingformtemplateid"))
				{
					return this.FormattedValues["msdynmkt_marketingformtemplateid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_marketingformtype")]
		public virtual msdynmkt_marketingformtype? msdynmkt_marketingformtype
		{
			get
			{
				return ((msdynmkt_marketingformtype?)(EntityOptionSetEnum.GetEnum(this, "msdynmkt_marketingformtype")));
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_marketingformtype");
				this.SetAttributeValue("msdynmkt_marketingformtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("msdynmkt_marketingformtype");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_marketingformtypename")]
		public string msdynmkt_marketingformtypeName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_marketingformtype"))
				{
					return this.FormattedValues["msdynmkt_marketingformtype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Matching Strategy associated with Form.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_matchingstrategyid")]
		public Microsoft.Xrm.Sdk.EntityReference msdynmkt_matchingstrategyid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdynmkt_matchingstrategyid");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_matchingstrategyid");
				this.SetAttributeValue("msdynmkt_matchingstrategyid", value);
				this.OnPropertyChanged("msdynmkt_matchingstrategyid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_matchingstrategyidname")]
		public string msdynmkt_matchingstrategyidName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_matchingstrategyid"))
				{
					return this.FormattedValues["msdynmkt_matchingstrategyid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Name of the Form
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_name")]
		public string msdynmkt_name
		{
			get
			{
				return this.GetAttributeValue<string>("msdynmkt_name");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_name");
				this.SetAttributeValue("msdynmkt_name", value);
				this.OnPropertyChanged("msdynmkt_name");
			}
		}
		
		/// <summary>
		/// (Deprecated) When selected it specified how to match existing contact
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_parentcontactmatchingstrategyid")]
		public Microsoft.Xrm.Sdk.EntityReference msdynmkt_parentcontactmatchingstrategyid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdynmkt_parentcontactmatchingstrategyid");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_parentcontactmatchingstrategyid");
				this.SetAttributeValue("msdynmkt_parentcontactmatchingstrategyid", value);
				this.OnPropertyChanged("msdynmkt_parentcontactmatchingstrategyid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_parentcontactmatchingstrategyidname")]
		public string msdynmkt_parentcontactmatchingstrategyidName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_parentcontactmatchingstrategyid"))
				{
					return this.FormattedValues["msdynmkt_parentcontactmatchingstrategyid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Placeholders
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_placeholders")]
		public string msdynmkt_placeholders
		{
			get
			{
				return this.GetAttributeValue<string>("msdynmkt_placeholders");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_placeholders");
				this.SetAttributeValue("msdynmkt_placeholders", value);
				this.OnPropertyChanged("msdynmkt_placeholders");
			}
		}
		
		/// <summary>
		/// (Deprecated) PortalPublishingStatus - use standalonepublishstatus instead
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_portalpublishingstatus")]
		public virtual msdynmkt_marketingform_msdynmkt_portalpublishingstatus? msdynmkt_portalpublishingstatus
		{
			get
			{
				return ((msdynmkt_marketingform_msdynmkt_portalpublishingstatus?)(EntityOptionSetEnum.GetEnum(this, "msdynmkt_portalpublishingstatus")));
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_portalpublishingstatus");
				this.SetAttributeValue("msdynmkt_portalpublishingstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("msdynmkt_portalpublishingstatus");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_portalpublishingstatusname")]
		public string msdynmkt_portalpublishingstatusName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_portalpublishingstatus"))
				{
					return this.FormattedValues["msdynmkt_portalpublishingstatus"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// (Deprecated) Portal Url
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_portalurl")]
		public string msdynmkt_portalurl
		{
			get
			{
				return this.GetAttributeValue<string>("msdynmkt_portalurl");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_portalurl");
				this.SetAttributeValue("msdynmkt_portalurl", value);
				this.OnPropertyChanged("msdynmkt_portalurl");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_postsubmissionactions")]
		public virtual msdynmkt_postsubmissionactions? msdynmkt_Postsubmissionactions
		{
			get
			{
				return ((msdynmkt_postsubmissionactions?)(EntityOptionSetEnum.GetEnum(this, "msdynmkt_postsubmissionactions")));
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_Postsubmissionactions");
				this.SetAttributeValue("msdynmkt_postsubmissionactions", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("msdynmkt_Postsubmissionactions");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_postsubmissionactionsname")]
		public string msdynmkt_postsubmissionactionsName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_postsubmissionactions"))
				{
					return this.FormattedValues["msdynmkt_postsubmissionactions"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// If enabled, form fields are prefilled by default.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_prefillfields")]
		public System.Nullable<bool> msdynmkt_prefillfields
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdynmkt_prefillfields");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_prefillfields");
				this.SetAttributeValue("msdynmkt_prefillfields", value);
				this.OnPropertyChanged("msdynmkt_prefillfields");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_prefillfieldsname")]
		public string msdynmkt_prefillfieldsName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_prefillfields"))
				{
					return this.FormattedValues["msdynmkt_prefillfields"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Redirect after submission
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_redirectenabled")]
		public System.Nullable<bool> msdynmkt_redirectenabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdynmkt_redirectenabled");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_redirectenabled");
				this.SetAttributeValue("msdynmkt_redirectenabled", value);
				this.OnPropertyChanged("msdynmkt_redirectenabled");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_redirectenabledname")]
		public string msdynmkt_redirectenabledName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_redirectenabled"))
				{
					return this.FormattedValues["msdynmkt_redirectenabled"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Redirect URL
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_redirecturl")]
		public string msdynmkt_redirecturl
		{
			get
			{
				return this.GetAttributeValue<string>("msdynmkt_redirecturl");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_redirecturl");
				this.SetAttributeValue("msdynmkt_redirecturl", value);
				this.OnPropertyChanged("msdynmkt_redirecturl");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_standalonehtml")]
		public string msdynmkt_standalonehtml
		{
			get
			{
				return this.GetAttributeValue<string>("msdynmkt_standalonehtml");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_standalonehtml");
				this.SetAttributeValue("msdynmkt_standalonehtml", value);
				this.OnPropertyChanged("msdynmkt_standalonehtml");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_standalonepublishstatus")]
		public virtual msdynmkt_msdynmkt_marketingform_msdynmkt_standalonepublishstatus? msdynmkt_standalonepublishstatus
		{
			get
			{
				return ((msdynmkt_msdynmkt_marketingform_msdynmkt_standalonepublishstatus?)(EntityOptionSetEnum.GetEnum(this, "msdynmkt_standalonepublishstatus")));
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_standalonepublishstatus");
				this.SetAttributeValue("msdynmkt_standalonepublishstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("msdynmkt_standalonepublishstatus");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_standalonepublishstatusname")]
		public string msdynmkt_standalonepublishstatusName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_standalonepublishstatus"))
				{
					return this.FormattedValues["msdynmkt_standalonepublishstatus"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Thank you notification
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_successmessage")]
		public string msdynmkt_successmessage
		{
			get
			{
				return this.GetAttributeValue<string>("msdynmkt_successmessage");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_successmessage");
				this.SetAttributeValue("msdynmkt_successmessage", value);
				this.OnPropertyChanged("msdynmkt_successmessage");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_targetaudience")]
		public Microsoft.Xrm.Sdk.EntityReference msdynmkt_targetaudience
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdynmkt_targetaudience");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_targetaudience");
				this.SetAttributeValue("msdynmkt_targetaudience", value);
				this.OnPropertyChanged("msdynmkt_targetaudience");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_targetaudiencename")]
		public string msdynmkt_targetaudienceName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_targetaudience"))
				{
					return this.FormattedValues["msdynmkt_targetaudience"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Audience
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_targetentity")]
		public string msdynmkt_targetentity
		{
			get
			{
				return this.GetAttributeValue<string>("msdynmkt_targetentity");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_targetentity");
				this.SetAttributeValue("msdynmkt_targetentity", value);
				this.OnPropertyChanged("msdynmkt_targetentity");
			}
		}
		
		/// <summary>
		/// Unique Name for the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_uniquename")]
		public string msdynmkt_uniquename
		{
			get
			{
				return this.GetAttributeValue<string>("msdynmkt_uniquename");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_uniquename");
				this.SetAttributeValue("msdynmkt_uniquename", value);
				this.OnPropertyChanged("msdynmkt_uniquename");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_updatecontact")]
		public virtual msdynmkt_formaudiencematchingchoice? msdynmkt_updatecontact
		{
			get
			{
				return ((msdynmkt_formaudiencematchingchoice?)(EntityOptionSetEnum.GetEnum(this, "msdynmkt_updatecontact")));
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_updatecontact");
				this.SetAttributeValue("msdynmkt_updatecontact", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("msdynmkt_updatecontact");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_updatecontactname")]
		public string msdynmkt_updatecontactName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_updatecontact"))
				{
					return this.FormattedValues["msdynmkt_updatecontact"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_updatelead")]
		public virtual msdynmkt_formaudiencematchingchoice? msdynmkt_updatelead
		{
			get
			{
				return ((msdynmkt_formaudiencematchingchoice?)(EntityOptionSetEnum.GetEnum(this, "msdynmkt_updatelead")));
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_updatelead");
				this.SetAttributeValue("msdynmkt_updatelead", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("msdynmkt_updatelead");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_updateleadname")]
		public string msdynmkt_updateleadName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_updatelead"))
				{
					return this.FormattedValues["msdynmkt_updatelead"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// (Deprecated) When selected we'll try to update parent contact with submitted data
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_updateparentcontact")]
		public System.Nullable<bool> msdynmkt_updateparentcontact
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdynmkt_updateparentcontact");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_updateparentcontact");
				this.SetAttributeValue("msdynmkt_updateparentcontact", value);
				this.OnPropertyChanged("msdynmkt_updateparentcontact");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_updateparentcontactname")]
		public string msdynmkt_updateparentcontactName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_updateparentcontact"))
				{
					return this.FormattedValues["msdynmkt_updateparentcontact"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Waitlisted notification
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_waitlistmessage")]
		public string msdynmkt_waitlistmessage
		{
			get
			{
				return this.GetAttributeValue<string>("msdynmkt_waitlistmessage");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_waitlistmessage");
				this.SetAttributeValue("msdynmkt_waitlistmessage", value);
				this.OnPropertyChanged("msdynmkt_waitlistmessage");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_webtracking")]
		public System.Nullable<bool> msdynmkt_webtracking
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdynmkt_webtracking");
			}
			set
			{
				this.OnPropertyChanging("msdynmkt_webtracking");
				this.SetAttributeValue("msdynmkt_webtracking", value);
				this.OnPropertyChanged("msdynmkt_webtracking");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdynmkt_webtrackingname")]
		public string msdynmkt_webtrackingName
		{
			get
			{
				if (this.FormattedValues.Contains("msdynmkt_webtracking"))
				{
					return this.FormattedValues["msdynmkt_webtracking"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// Status of the Form
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual msdynmkt_marketingform_statecode? statecode
		{
			get
			{
				return ((msdynmkt_marketingform_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string statecodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Form
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual msdynmkt_marketingform_statuscode? statuscode
		{
			get
			{
				return ((msdynmkt_marketingform_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string statuscodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
	}
}
#pragma warning restore CS1591
